import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, Image, TouchableOpacity, Linking, Alert } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import * as Print from 'expo-print';
import * as FileSystem from 'expo-file-system';
import { WebView } from 'react-native-webview';

const Chalazion = () => {
  const [pdfUri, setPdfUri] = useState(null); // State to store the base64 PDF URI

  // Function to open external links
  const openLink = (url) => {
    Linking.openURL(url).catch((err) => console.error('Failed to open link:', err));
  };

  // Function to generate and view PDF report
  const generatePDFReport = async () => {
    const htmlContent = `
     <html>
  <body>
    <h1>Chalazion Report</h1>

    <h2>What is a Chalazion?</h2>
    <p>
      A chalazion is a small, painless lump or swelling that appears on the eyelid due to a blocked meibomian gland. The meibomian glands are responsible for producing oil that lubricates the eye. When one of these glands gets blocked, a chalazion can form.
    </p>

    <h2>Symptoms</h2>
    <ul>
      <li>A small, painless bump on the eyelid</li>
      <li>Swelling and redness in the affected area</li>
      <li>Blurred vision (if the chalazion is large enough to put pressure on the cornea)</li>
      <li>Sensitivity to light</li>
    </ul>

    <h2>Possible Causes</h2>
    <p>
      Chalazions are typically caused by a blockage of the oil glands in the eyelids. They can be related to:
    </p>
    <ul>
      <li>Poor hygiene around the eyes</li>
      <li>Chronic blepharitis (inflammation of the eyelids)</li>
      <li>Skin conditions such as rosacea</li>
      <li>Hormonal changes, especially in people with oily skin</li>
    </ul>

    <h2>Treatments</h2>
    <p>
      Most chalazions will go away on their own within a few weeks. However, treatment can help speed up the healing process or reduce discomfort. Common treatments include:
    </p>
    <ul>
      <li><strong>Warm Compresses:</strong> Applying a warm compress to the affected eyelid for 10-15 minutes a few times a day can help soften the oil and promote drainage.</li>
      <li><strong>Gentle Massage:</strong> After applying a warm compress, gently massaging the area can help open the blocked gland.</li>
      <li><strong>Topical Medications:</strong> If an infection is present, antibiotics or steroid creams may be prescribed.</li>
      <li><strong>Surgical Drainage:</strong> In some cases, a doctor may need to surgically drain the chalazion if it does not resolve with other treatments.</li>
    </ul>

    <h2>When to See a Doctor</h2>
    <p>
      It’s important to see a doctor if:
    </p>
    <ul>
      <li>The chalazion doesn't improve or worsens despite treatment.</li>
      <li>The chalazion is causing significant discomfort or pain.</li>
      <li>You experience vision problems, such as blurred vision.</li>
    </ul>

    <h2>Prevention</h2>
    <p>
      To prevent chalazions from forming, consider the following tips:
    </p>
    <ul>
      <li>Maintain good hygiene around your eyes by cleaning your eyelids regularly.</li>
      <li>Remove makeup before going to bed.</li>
      <li>Avoid touching your eyes with dirty hands.</li>
      <li>If you wear contact lenses, make sure they are clean and follow the recommended guidelines for use.</li>
    </ul>

    <h2>External Resources</h2>
    <p>For more information on Chalazion, you can visit the following trusted resources:</p>
    <ul>
      <li><a href="https://www.mayoclinic.org/diseases-conditions/chalazion/symptoms-causes/syc-20354941" target="_blank">Mayo Clinic - Chalazion</a></li>
      <li><a href="https://www.webmd.com/eye-health/chalazion" target="_blank">WebMD - Chalazion</a></li>
    </ul>

    <footer>
      <p>Report generated by your Chalazion Information App</p>
    </footer>
  </body>
</html>
    `;

    try {
      // Generate the PDF file
      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      console.log('PDF generated at:', uri);

      // Update state with the PDF URI to display in WebView
      setPdfUri(uri);

      // Show a success message
      Alert.alert('Success', 'PDF generated successfully!');
    } catch (error) {
      Alert.alert('Error', 'Failed to generate PDF file.');
      console.error('Failed to generate PDF:', error);
    }
  };
  return (
    <ScrollView contentContainerStyle={styles.scrollContainer}>
      <LinearGradient
        colors={['#6a11cb', '#2575fc']}
        style={styles.gradientBackground}
      >
        <Text style={styles.title}>Chalazion</Text>
      </LinearGradient>

      <View style={styles.contentContainer}>
        {/* Introduction Section */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>What is a Chalazion?</Text>
          <Text style={styles.cardText}>
            A chalazion is a small, painless lump or swelling on the eyelid caused by a blockage in one of the tiny oil glands (meibomian glands) near the eyelashes. It is not usually serious but can be uncomfortable or cosmetically bothersome.
          </Text>
          <Image
            source={require('./Chalazion.jpg')} // Replace with a real image URL
            style={styles.image}
          />
        </View>

        {/* Symptoms Section */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Symptoms</Text>
          <Text style={styles.cardText}>
            - A small, painless bump on the eyelid {'\n'}
            - Swelling or tenderness{'\n'}
            - Redness or irritation {'\n'}
            - Blurred vision (if the chalazion is large) {'\n'}
          </Text>
        </View>

        {/* Treatments Section */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Treatments</Text>
          <Text style={styles.cardText}>
            <Text style={{ fontWeight: 'bold' }}>- Warm Compresses:</Text> Apply a warm, damp cloth to the eyelid for 10-15 minutes, 3-5 times a day. {'\n'}
            <Text style={{ fontWeight: 'bold' }}>- Massage:</Text> Gently massage the area to help drain the blocked gland.{'\n'}
            <Text style={{ fontWeight: 'bold' }}>- Medications:</Text> Use antibiotic ointments or steroid injections if prescribed by a doctor.{'\n'}
            <Text style={{ fontWeight: 'bold' }}>- Surgery:</Text> In rare cases, a minor surgical procedure may be needed to remove the chalazion.{'\n'}
          </Text>
        </View>

        {/* PDF Report Button */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Diagnosis Report</Text>
          <TouchableOpacity
            style={styles.linkButton}
            onPress={generatePDFReport}
          >
            <Text style={styles.linkButtonText}>Generate PDF Report</Text>
          </TouchableOpacity>
        </View>

        {/* Display PDF in WebView */}
        {pdfUri && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>Generated Report</Text>
            <WebView
              source={{ uri: pdfUri }}
              style={styles.webview}
              originWhitelist={['*']} // Allow all origins
              javaScriptEnabled={true} // Enable JavaScript
              domStorageEnabled={true} // Enable DOM storage
            />
          </View>
        )}

        {/* External Resources */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Learn More</Text>
          <TouchableOpacity
            style={styles.linkButton}
            onPress={() => openLink('https://www.mayoclinic.org/diseases-conditions/chalazion/symptoms-causes/syc-20354941')}
          >
            <Text style={styles.linkButtonText}>Mayo Clinic - Chalazion</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.linkButton}
            onPress={() => openLink('https://www.webmd.com/eye-health/chalazion')}
          >
            <Text style={styles.linkButtonText}>WebMD - Chalazion</Text>
          </TouchableOpacity>
        </View>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  scrollContainer: {
    flexGrow: 1,
    backgroundColor: '#f0f0f0',
  },
  gradientBackground: {
    paddingVertical: 30,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    alignItems: 'center',
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
  },
  contentContainer: {
    padding: 20,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 5,
  },
  cardTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
  },
  cardText: {
    fontSize: 16,
    color: '#666',
    lineHeight: 24,
  },
  image: {
    width: '100%',
    height: 200,
    borderRadius: 10,
    marginTop: 10,
  },
  linkButton: {
    backgroundColor: '#2575fc',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginTop: 10,
    alignItems: 'center',
  },
  linkButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  webview: {
    width: '100%',
    height: 500, // Adjust height as needed
    marginTop: 10,
  },
});

export default Chalazion;